-------------------------------------------------------------------------------------------
-- ACCOUNT
-------------------------------------------------------------------------------------------
CREATE TABLE ACCOUNT
(
  ACCOUNT_ID		INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  ACCOUNT_TYPE		VARCHAR(200)	NOT NULL,
  CREATION_DATE		TIMESTAMP		NOT NULL,
  BALANCE			BIGINT			NOT NULL
);